export const APP_SET_CURRENT_STEP = "APP_SET_CURRENT_STEP"
export const APP_CONFIG_RESET = "APP_CONFIG_RESET"

export const ENGINE_LOAD_STARTED = "ENGINE_LOAD_STARTED"
export const ENGINE_LOAD_SUCCESS = "ENGINE_LOAD_SUCCESS"
export const ENGINE_LOAD_FAILURE = "ENGINE_LOAD_FAILURE"

export const ENGINE_LIST_STARTED = "ENGINE_LIST_STARTED"
export const ENGINE_LIST_SUCCESS = "ENGINE_LIST_SUCCESS"
export const ENGINE_LIST_FAILURE = "ENGINE_LIST_FAILURE"

export const CONFIG_OBJECT_NAMES_STARTED = "CONFIG_OBJECT_NAMES_STARTED"
export const CONFIG_OBJECT_NAMES_SUCCESS = "CONFIG_OBJECT_NAMES_SUCCESS"
export const CONFIG_OBJECT_NAMES_FAILURE = "CONFIG_OBJECT_NAMES_FAILURE"

export const LIST_APP_CONFIG_STARTED = "LIST_APP_CONFIG_STARTED"
export const LIST_APP_CONFIG_SUCCESS = "LIST_APP_CONFIG_SUCCESS"
export const LIST_APP_CONFIG_FAILURE = "LIST_APP_CONFIG_FAILURE"

