export const MODEL_NEW_UNSTARTED = "MODEL_NEW_UNSTARTED";
export const MODEL_NEW_STARTED = "MODEL_NEW_STARTED";
export const MODEL_NEW_SUCCESS = "MODEL_NEW_SUCCESS";
export const MODEL_NEW_FAILURE = "MODEL_NEW_FAILURE";
//
export const MODEL_LOAD_UNSTARTED = "MODEL_LOAD_UNSTARTED";
export const MODEL_LOAD_STARTED = "MODEL_LOAD_STARTED";
export const MODEL_LOAD_SUCCESS = "MODEL_LOAD_SUCCESS";
export const MODEL_LOAD_FAILURE = "MODEL_LOAD_FAILURE";
//
export const MODEL_LIST_UNSTARTED = "MODEL_LIST_UNSTARTED";
export const MODEL_LIST_STARTED = "MODEL_LIST_STARTED";
export const MODEL_LIST_SUCCESS = "MODEL_LIST_SUCCESS";
export const MODEL_LIST_FAILURE = "MODEL_LIST_FAILURE";
//
export const MODEL_SETTINGS_UNSTARTED = "MODEL_SETTINGS_UNSTARTED";
export const MODEL_SETTINGS_STARTED = "MODEL_SETTINGS_STARTED";
export const MODEL_SETTINGS_SUCCESS = "MODEL_SETTINGS_SUCCESS";
export const MODEL_SETTINGS_FAILURE = "MODEL_SETTINGS_FAILURE";
//
export const MODEL_TRAIN_UNSTARTED = "MODEL_TRAIN_UNSTARTED";
export const MODEL_TRAIN_STARTED = "MODEL_TRAIN_STARTED";
export const MODEL_TRAIN_SUCCESS = "MODEL_TRAIN_SUCCESS";
export const MODEL_TRAIN_FAILURE = "MODEL_TRAIN_FAILURE";
//
export const MODEL_STATUS_UNSTARTED = "MODEL_STATUS_UNSTARTED";
export const MODEL_STATUS_STARTED = "MODEL_STATUS_STARTED";
export const MODEL_STATUS_SUCCESS = "MODEL_STATUS_SUCCESS";
export const MODEL_STATUS_FAILURE = "MODEL_STATUS_FAILURE";
//
export const MODEL_RESULTS_UNSTARTED = "MODEL_RESULTS_UNSTARTED";
export const MODEL_RESULTS_STARTED = "MODEL_RESULTS_STARTED";
export const MODEL_RESULTS_SUCCESS = "MODEL_RESULTS_SUCCESS";
export const MODEL_RESULTS_FAILURE = "MODEL_RESULTS_FAILURE";
//
export const MODEL_GET_LOG_UNSTARTED = "MODEL_GET_LOG_UNSTARTED";
export const MODEL_GET_LOG_STARTED = "MODEL_GET_LOG_STARTED";
export const MODEL_GET_LOG_SUCCESS = "MODEL_GET_LOG_SUCCESS";
export const MODEL_GET_LOG_FAILURE = "MODEL_GET_LOG_FAILURE";
