export const TRANSCRIPTION_NEW_UNSTARTED = "TRANSCRIPTION_NEW_UNSTARTED";
export const TRANSCRIPTION_NEW_STARTED = "TRANSCRIPTION_NEW_STARTED";
export const TRANSCRIPTION_NEW_SUCCESS = "TRANSCRIPTION_NEW_SUCCESS";
export const TRANSCRIPTION_NEW_FAILURE = "TRANSCRIPTION_NEW_FAILURE";
//
export const TRANSCRIPTION_STATUS_UNSTARTED = "TRANSCRIPTION_STATUS_UNSTARTED";
export const TRANSCRIPTION_STATUS_STARTED = "TRANSCRIPTION_STATUS_STARTED";
export const TRANSCRIPTION_STATUS_SUCCESS = "TRANSCRIPTION_STATUS_SUCCESS";
export const TRANSCRIPTION_STATUS_FAILURE = "TRANSCRIPTION_STATUS_FAILURE";
//
export const TRANSCRIPTION_TRANSCRIBE_UNSTARTED = "TRANSCRIPTION_TRANSCRIBE_UNSTARTED";
export const TRANSCRIPTION_TRANSCRIBE_STARTED = "TRANSCRIPTION_TRANSCRIBE_STARTED";
export const TRANSCRIPTION_TRANSCRIBE_SUCCESS = "TRANSCRIPTION_TRANSCRIBE_SUCCESS";
export const TRANSCRIPTION_TRANSCRIBE_FAILURE = "TRANSCRIPTION_TRANSCRIBE_FAILURE";
//
export const TRANSCRIPTION_GET_TEXT_UNSTARTED = "TRANSCRIPTION_GET_TEXT_UNSTARTED";
export const TRANSCRIPTION_GET_TEXT_STARTED = "TRANSCRIPTION_GET_TEXT_STARTED";
export const TRANSCRIPTION_GET_TEXT_SUCCESS = "TRANSCRIPTION_GET_TEXT_SUCCESS";
export const TRANSCRIPTION_GET_TEXT_FAILURE = "TRANSCRIPTION_GET_TEXT_FAILURE";
//
export const TRANSCRIPTION_GET_ELAN_UNSTARTED = "TRANSCRIPTION_GET_ELAN_UNSTARTED";
export const TRANSCRIPTION_GET_ELAN_STARTED = "TRANSCRIPTION_GET_ELAN_STARTED";
export const TRANSCRIPTION_GET_ELAN_SUCCESS = "TRANSCRIPTION_GET_ELAN_SUCCESS";
export const TRANSCRIPTION_GET_ELAN_FAILURE = "TRANSCRIPTION_GET_ELAN_FAILURE";
