

##################### server tasks
new-model:
  desc: "clear files for a new model to be made"
  cmds:
    - rm -rf /elpis/current_model/*

transfer-model-to-kaldi:
  desc: "move model files from local server to kaldi space"
  cmds:
    - rm -rf /kaldi-helpers/working_dir/input
    - mkdir -p /kaldi-helpers/working_dir/input
    - mv /elpis/current_model/* /kaldi-helpers/working_dir/input/

transfer-transcription-to-kaldi:
  desc: "move transcription files from local server to kaldi space"
  cmds:
    - rm -rf /kaldi-helpers/working_dir/input/infer
    - mkdir -p /kaldi-helpers/working_dir/input/infer
    - mv /elpis/current_transcription/* /kaldi-helpers/working_dir/input/infer/

process-infer-files:
  desc: ""
  cmds:
    - python3.6 /kaldi-helpers/kaldi_helpers/input/elan_to_json.py
                --input_dir /kaldi-helpers/working_dir/input/infer
                --output_dir /tmp/out
                --tier Phrase
                --output_json /tmp/dirty.json
    - python3.6 /kaldi-helpers/kaldi_helpers/input/json_to_kaldi.py
                --input_json /tmp/dirty.json
                --output_folder /tmp/json_splitted
                --corpus_txt working_dir/input/output/tmp/corpus.txt
                --text_corpus /kaldi-helpers/working_dir/input/config/text_corpora

#  This is useful for resetting when using the CLI (July 2020)
reset-state:
  desc: "clear state dir"
  cmds:
    - rm -rf /state/*
    - mkdir /state
    - touch  /state/interface.json

