export const APP_SET_CURRENT_STEP = "APP_SET_CURRENT_STEP"
export const APP_CONFIG_RESET = "APP_CONFIG_RESET"

export const ENGINE_LOAD_STARTED = "ENGINE_LOAD_STARTED"
export const ENGINE_LOAD_SUCCESS = "ENGINE_LOAD_SUCCESS"
export const ENGINE_LOAD_FAILURE = "ENGINE_LOAD_FAILURE"
export const ENGINE_LIST_STARTED = "ENGINE_LIST_STARTED"
export const ENGINE_LIST_SUCCESS = "ENGINE_LIST_SUCCESS"
export const ENGINE_LIST_FAILURE = "ENGINE_LIST_FAILURE"
