export const DATASET_NEW_UNSTARTED = "DATASET_NEW_UNSTARTED"
export const DATASET_NEW_STARTED   = "DATASET_NEW_STARTED"
export const DATASET_NEW_SUCCESS   = "DATASET_NEW_SUCCESS"
export const DATASET_NEW_FAILURE   = "DATASET_NEW_FAILURE"

export const DATASET_LOAD_UNSTARTED = "DATASET_LOAD_UNSTARTED"
export const DATASET_LOAD_STARTED   = "DATASET_LOAD_STARTED"
export const DATASET_LOAD_SUCCESS   = "DATASET_LOAD_SUCCESS"
export const DATASET_LOAD_FAILURE   = "DATASET_LOAD_FAILURE"

export const DATASET_DELETE_UNSTARTED = "DATASET_DELETE_UNSTARTED"
export const DATASET_DELETE_STARTED   = "DATASET_DELETE_STARTED"
export const DATASET_DELETE_SUCCESS   = "DATASET_DELETE_SUCCESS"
export const DATASET_DELETE_FAILURE   = "DATASET_DELETE_FAILURE"

export const DATASET_LIST_UNSTARTED = "DATASET_LIST_UNSTARTED"
export const DATASET_LIST_STARTED   = "DATASET_LIST_STARTED"
export const DATASET_LIST_SUCCESS   = "DATASET_LIST_SUCCESS"
export const DATASET_LIST_FAILURE   = "DATASET_LIST_FAILURE"

export const DATASET_FILES_UNSTARTED = "DATASET_FILES_UNSTARTED"
export const DATASET_FILES_STARTED   = "DATASET_FILES_STARTED"
export const DATASET_FILES_SUCCESS   = "DATASET_FILES_SUCCESS"
export const DATASET_FILES_FAILURE   = "DATASET_FILES_FAILURE"

export const DATASET_SETTINGS_UNSTARTED = "DATASET_SETTINGS_UNSTARTED"
export const DATASET_SETTINGS_STARTED   = "DATASET_SETTINGS_STARTED"
export const DATASET_SETTINGS_SUCCESS   = "DATASET_SETTINGS_SUCCESS"
export const DATASET_SETTINGS_FAILURE   = "DATASET_SETTINGS_FAILURE"

export const DATASET_PREPARE_UNSTARTED = "DATASET_PREPARE_UNSTARTED"
export const DATASET_PREPARE_STARTED   = "DATASET_PREPARE_STARTED"
export const DATASET_PREPARE_SUCCESS   = "DATASET_PREPARE_SUCCESS"
export const DATASET_PREPARE_FAILURE   = "DATASET_PREPARE_FAILURE"

export const DATASET_UI_UPDATE_UNSTARTED = "DATASET_UI_UPDATE_UNSTARTED"
export const DATASET_UI_UPDATE_STARTED   = "DATASET_UI_UPDATE_STARTED"
export const DATASET_UI_UPDATE_SUCCESS   = "DATASET_UI_UPDATE_SUCCESS"
export const DATASET_UI_UPDATE_FAILURE   = "DATASET_UI_UPDATE_FAILURE"
