export const MODEL_NEW_UNSTARTED = "MODEL_NEW_UNSTARTED"
export const MODEL_NEW_STARTED   = "MODEL_NEW_STARTED"
export const MODEL_NEW_SUCCESS   = "MODEL_NEW_SUCCESS"
export const MODEL_NEW_FAILURE   = "MODEL_NEW_FAILURE"

export const MODEL_LOAD_UNSTARTED = "MODEL_LOAD_UNSTARTED"
export const MODEL_LOAD_STARTED   = "MODEL_LOAD_STARTED"
export const MODEL_LOAD_SUCCESS   = "MODEL_LOAD_SUCCESS"
export const MODEL_LOAD_FAILURE   = "MODEL_LOAD_FAILURE"

export const MODEL_LIST_UNSTARTED = "MODEL_LIST_UNSTARTED"
export const MODEL_LIST_STARTED = "MODEL_LIST_STARTED"
export const MODEL_LIST_SUCCESS = "MODEL_LIST_SUCCESS"
export const MODEL_LIST_FAILURE = "MODEL_LIST_FAILURE"

export const MODEL_SETTINGS_UNSTARTED = "MODEL_SETTINGS_UNSTARTED"
export const MODEL_SETTINGS_STARTED   = "MODEL_SETTINGS_STARTED"
export const MODEL_SETTINGS_SUCCESS   = "MODEL_SETTINGS_SUCCESS"
export const MODEL_SETTINGS_FAILURE   = "MODEL_SETTINGS_FAILURE"
