export const PRON_DICT_NEW_UNSTARTED = "PRON_DICT_NEW_UNSTARTED"
export const PRON_DICT_NEW_STARTED   = "PRON_DICT_NEW_STARTED"
export const PRON_DICT_NEW_SUCCESS   = "PRON_DICT_NEW_SUCCESS"
export const PRON_DICT_NEW_FAILURE   = "PRON_DICT_NEW_FAILURE"

export const PRON_DICT_LOAD_UNSTARTED = "PRON_DICT_LOAD_UNSTARTED"
export const PRON_DICT_LOAD_STARTED   = "PRON_DICT_LOAD_STARTED"
export const PRON_DICT_LOAD_SUCCESS   = "PRON_DICT_LOAD_SUCCESS"
export const PRON_DICT_LOAD_FAILURE   = "PRON_DICT_LOAD_FAILURE"

export const PRON_DICT_LIST_UNSTARTED = "PRON_DICT_LIST_UNSTARTED"
export const PRON_DICT_LIST_STARTED   = "PRON_DICT_LIST_STARTED"
export const PRON_DICT_LIST_SUCCESS   = "PRON_DICT_LIST_SUCCESS"
export const PRON_DICT_LIST_FAILURE   = "PRON_DICT_LIST_FAILURE"

export const PRON_DICT_L2S_UNSTARTED = "PRON_DICT_L2S_UNSTARTED"
export const PRON_DICT_L2S_STARTED   = "PRON_DICT_L2S_STARTED"
export const PRON_DICT_L2S_SUCCESS   = "PRON_DICT_L2S_SUCCESS"
export const PRON_DICT_L2S_FAILURE   = "PRON_DICT_L2S_FAILURE"

export const PRON_DICT_BUILD_LEXICON_UNSTARTED = "PRON_DICT_BUILD_LEXICON_UNSTARTED"
export const PRON_DICT_BUILD_LEXICON_STARTED   = "PRON_DICT_BUILD_LEXICON_STARTED"
export const PRON_DICT_BUILD_LEXICON_SUCCESS   = "PRON_DICT_BUILD_LEXICON_SUCCESS"
export const PRON_DICT_BUILD_LEXICON_FAILURE   = "PRON_DICT_BUILD_LEXICON_FAILURE"

export const PRON_DICT_SAVE_LEXICON_UNSTARTED = "PRON_DICT_SAVE_LEXICON_UNSTARTED"
export const PRON_DICT_SAVE_LEXICON_STARTED   = "PRON_DICT_SAVE_LEXICON_STARTED"
export const PRON_DICT_SAVE_LEXICON_SUCCESS   = "PRON_DICT_SAVE_LEXICON_SUCCESS"
export const PRON_DICT_SAVE_LEXICON_FAILURE   = "PRON_DICT_SAVE_LEXICON_FAILURE"

export const PRON_DICT_UPDATE_LEXICON = "PRON_DICT_UPDATE_LEXICON"

