export const TRANSCRIPTION_NEW_UNSTARTED = "TRANSCRIPTION_NEW_UNSTARTED"
export const TRANSCRIPTION_NEW_STARTED   = "TRANSCRIPTION_NEW_STARTED"
export const TRANSCRIPTION_NEW_SUCCESS   = "TRANSCRIPTION_NEW_SUCCESS"
export const TRANSCRIPTION_NEW_FAILURE   = "TRANSCRIPTION_NEW_FAILURE"
