export const DATASET_NEW_UNSTARTED = "DATASET_NEW_UNSTARTED"
export const DATASET_NEW_STARTED = "DATASET_NEW_STARTED"
export const DATASET_NEW_SUCCESS = "DATASET_NEW_SUCCESS"
export const DATASET_NEW_FAILURE = "DATASET_NEW_FAILURE"

export const DATASET_LOAD_UNSTARTED = "DATASET_LOAD_UNSTARTED"
export const DATASET_LOAD_STARTED = "DATASET_LOAD_STARTED"
export const DATASET_LOAD_SUCCESS = "DATASET_LOAD_SUCCESS"
export const DATASET_LOAD_FAILURE = "DATASET_LOAD_FAILURE"
